name: CI/CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o gonotif

      - name: Kill running app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          script_stop: false
          script: |
            pkill -f "/root/go/src/gonotif/gonotif" || true
            sleep 2
            echo "Done"

      - name: Upload binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          source: "gonotif"
          target: "/root/go/src/gonotif/"
          overwrite: true

      - name: Restart App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          script: |
            cd /root/go/src/gonotif
            nohup ./gonotif > out.log 2>&1 &
            echo "App started"